import { StateWholesaleRule, MarketNewsTicker } from "../types";

export const STATE_WHOLESALE_RULES: Record<string, StateWholesaleRule> = {
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    licenseStatus: "LICENSE_REQUIRED",
    badgeLabel: "License Required (SB 927)",
    badgeColor: "red",
    statute: "Oklahoma SB 927 (Predatory Wholesaler Act)",
    summary: "Oklahoma strictly prohibits marketing equitable interest or assigning contracts without holding an active real estate broker or sales associate license.",
    recommendedStrategy: "Double Close (A-B/B-C)",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Misdemeanor criminal charges, civil fines up to $5,000 per violation, and permanent injunctions by OREC.",
    compliantClauses: [
      "No public marketing of property prior to taking actual fee simple title.",
      "Close A-to-B transaction with separate transactional funding before executing B-to-C resale.",
      "Or operate strictly as a licensed real estate licensee under an Oklahoma sponsoring broker.",
    ],
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    licenseStatus: "LICENSE_REQUIRED",
    badgeLabel: "License Required (>1 Deal/Yr - SB 1872)",
    badgeColor: "red",
    statute: "Illinois Real Estate License Act (225 ILCS 454/1-10 & SB 1872)",
    summary: "Illinois defines wholesaling or assigning more than ONE (1) residential purchase contract per 12-month period as requiring a real estate license.",
    recommendedStrategy: "Double Close (A-B/B-C)",
    earnestMoneyStandard: "$10 - $100 Token",
    penaltiesSummary: "IDFPR civil penalties up to $25,000 per unlicensed transaction and mandatory disgorgement of assignment profits.",
    compliantClauses: [
      "Limit direct assignment of contracts to maximum 1 deal per rolling 12 months.",
      "For subsequent deals: Use transactional funding double-closing or purchase through a newly formed entity and sell LLC units.",
    ],
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania (Philadelphia)",
    licenseStatus: "LICENSE_REQUIRED",
    badgeLabel: "License / Local Permit (Bill 200494)",
    badgeColor: "red",
    statute: "Philadelphia Residential Wholesaler Licensing Ordinance (Bill 200494)",
    summary: "Philadelphia requires a commercial wholesale license and specific homeowner rights disclosures before making offers. State level allows equitable interest if properly disclosed.",
    recommendedStrategy: "Double Close (A-B/B-C)",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Local municipal fines up to $2,000 per day and contract nullification if unlicensed.",
    compliantClauses: [
      "Obtain Philadelphia Wholesale License endorsement prior to soliciting homeowners.",
      "Deliver Fair Market Value Disclosure Form to seller minimum 3 business days prior to contract signing.",
    ],
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    licenseStatus: "LICENSE_REQUIRED",
    badgeLabel: "License Required (Act 236)",
    badgeColor: "red",
    statute: "South Carolina Real Estate License Law Act 236 / S. 1017",
    summary: "Prohibits publicly advertising, marketing, or soliciting a contract for sale or assignment of an equitable interest without an active real estate broker license.",
    recommendedStrategy: "Double Close (A-B/B-C)",
    earnestMoneyStandard: "$500 - $2,500 Typical",
    penaltiesSummary: "LLR fines up to $5,000 and misdemeanor charges.",
    compliantClauses: [
      "Must take legal title via Double Closing or utilize Novation Agreement with a licensed SC broker.",
    ],
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    licenseStatus: "LICENSE_REQUIRED",
    badgeLabel: "License Required (Act 1072)",
    badgeColor: "red",
    statute: "Arkansas Real Estate Commission Act 1072",
    summary: "Classifies wholesaling and equitable interest assignment as real estate brokerage requiring a license, unless purchasing as a principal owner.",
    recommendedStrategy: "Double Close (A-B/B-C)",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Class D felony risk for persistent unlicensed brokerage activity.",
    compliantClauses: [
      "Must double close with transactional funds or hold active AR license.",
    ],
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    licenseStatus: "DISCLOSURE_REQUIRED",
    badgeLabel: "Disclosure Required (TREC §1101.0045)",
    badgeColor: "amber",
    statute: "Texas Occupations Code §1101.0045 & Senate Bill 2212",
    summary: "Wholesaling is legal without a license provided you strictly market YOUR EQUITABLE INTEREST in the contract and never market the physical real estate itself. Mandatory statutory disclosure required.",
    recommendedStrategy: "Equitable Interest Disclosure",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "TREC fines up to $5,000/day and treble damages under Texas Deceptive Trade Practices Act (DTPA).",
    compliantClauses: [
      "MANDATORY CLAUSE: 'Buyer does not possess legal title to the property and is solely conveying its contractual equitable interest as Buyer under the original purchase agreement.'",
      "All public and private marketing must state: 'ASSIGNMENT OF CONTRACT ONLY - NOT AGENT OF OWNER'.",
    ],
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    licenseStatus: "DISCLOSURE_REQUIRED",
    badgeLabel: "Disclosure Required (HB 2747)",
    badgeColor: "amber",
    statute: "Arizona Revised Statutes § 32-2181 & HB 2747",
    summary: "Wholesalers must provide written statutory disclosure to both seller and end buyer prior to contract execution stating they hold equitable interest and intend to assign for profit.",
    recommendedStrategy: "Equitable Interest Disclosure",
    earnestMoneyStandard: "$10 - $100 Token",
    penaltiesSummary: "Contracts voidable by seller, restitution of assignment fee, ADRE civil penalties.",
    compliantClauses: [
      "Written disclosure to Seller that Buyer is an investor seeking to assign for compensation.",
      "Buyer must not advertise the property on MLS without a broker listing agreement.",
    ],
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    licenseStatus: "DISCLOSURE_REQUIRED",
    badgeLabel: "Equitable Disclosure (F.S. §475.43)",
    badgeColor: "amber",
    statute: "Florida Statutes Chapter 475 § 475.43",
    summary: "Direct contract assignment is legal. Wholesaler must disclose they do not hold legal title and are selling equitable interest. Cannot represent seller or advertise property like a licensed agent.",
    recommendedStrategy: "Equitable Interest Disclosure",
    earnestMoneyStandard: "$10 - $100 Token",
    penaltiesSummary: "FREC investigations for unlicensed practice and potential contract rescission.",
    compliantClauses: [
      "Include Florida equitable interest disclosure in all assignment addenda.",
      "No public signage or agent-style advertising without explicit seller authorization.",
    ],
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    licenseStatus: "DISCLOSURE_REQUIRED",
    badgeLabel: "Disclosure Required (NCREC Bulletin)",
    badgeColor: "amber",
    statute: "North Carolina Real Estate Commission Bulletin (NCREC §93A)",
    summary: "Assignment of contract is permissible under common law, but marketing the physical property without legal title violates NCREC rules. Must market only the contract right.",
    recommendedStrategy: "Equitable Interest Disclosure",
    earnestMoneyStandard: "$500 - $2,500 Typical",
    penaltiesSummary: "Injunctions and civil actions by NCREC.",
    compliantClauses: [
      "Market exclusively to a private buyers list as an assignment of contract rights.",
    ],
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Michigan Occupational Code Act 299 of 1980 (MCL 339.2501)",
    summary: "Michigan fully recognizes equitable interest assignment under contract law. Wholesalers can assign purchase agreements with or without earnest money deposit.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Standard contract law rules apply. No licensing mandate for assigning own contracts.",
    compliantClauses: [
      "Standard assignability clause: 'Buyer reserves the right to assign this agreement to any third party.'",
      "Earnest money optional — zero dollar deposit valid upon mutual consideration.",
    ],
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Ohio Revised Code § 4735.01",
    summary: "Ohio allows direct assignment of real estate purchase contracts. Wholesaler must act as principal to the contract and disclose equitable interest assignment.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Standard civil contract compliance.",
    compliantClauses: [
      "Assignability clause permitted without broker affiliation.",
      "Closing via title company or attorney.",
    ],
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Tennessee Real Estate Broker License Act (TCA § 62-13-104)",
    summary: "Principals buying on their own account and assigning equitable rights are exempt from licensure. Tennessee courts uphold wholesale contract assignments.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Standard contractual remedies.",
    compliantClauses: [
      "Full assignment clause with buyer right to select title/escrow company.",
    ],
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Indiana Code § 25-34.1-3-2",
    summary: "Assignment of contractual interest is lawful without real estate license. Clear equitable interest disclosures recommended for best practice.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "None for principal contract assignments.",
    compliantClauses: [
      "Standard wholesale purchase agreement with inspection contingencies.",
    ],
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Missouri Revised Statutes Chapter 339 (RSMo § 339.010)",
    summary: "Missouri allows standard wholesale assignments when executed as a principal. Ensure contracts include explicit right of assignment.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "MREC regulations apply if acting as an unlicensed third-party broker.",
    compliantClauses: [
      "Right to assign clause with zero earnest money or nominal consideration.",
    ],
  },
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Code of Alabama § 34-27-30",
    summary: "Alabama permits contract assignments under principal doctrine. Earnest money deposit is negotiable between buyer and seller ($0 allowed).",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "AREC enforcement if representing others for a fee without principal contract.",
    compliantClauses: [
      "Direct assignment clause with 10-day inspection contingency.",
    ],
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Official Code of Georgia Annotated (OCGA § 43-40-29)",
    summary: "Georgia permits principals to buy and assign purchase contracts. Closing must be handled by a licensed Georgia attorney.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "$10 - $100 Token",
    penaltiesSummary: "GREC unlicensed broker penalties if not named as buyer in original contract.",
    compliantClauses: [
      "Georgia closing attorney stipulation clause with assignment rights.",
    ],
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "Maryland Real Estate Commission Title 17",
    summary: "Wholesaling via assignment is permitted. Must disclose non-owner equitable interest status in Baltimore City / Maryland transactions.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "MREC investigations if misrepresenting ownership.",
    compliantClauses: [
      "Equitable interest disclosure clause with right to assign.",
    ],
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed (Attorney State)",
    badgeColor: "emerald",
    statute: "NY Real Property Law § 440 & Common Law Assignment",
    summary: "New York is an attorney closing state. Contract assignments are fully legal provided contracts are not barred from assignment and transfer taxes are accounted for.",
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "$500 - $2,500 Typical",
    penaltiesSummary: "DOS investigations for unlicensed broker activity without contract interest.",
    compliantClauses: [
      "Attorney approval contingency clause (3-5 business days).",
      "Explicit right to assign to LLC or qualified third-party buyer.",
    ],
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    licenseStatus: "DISCLOSURE_REQUIRED",
    badgeLabel: "Disclosure Required (Cal. B&P §10131)",
    badgeColor: "amber",
    statute: "California Business and Professions Code § 10131",
    summary: "California permits assignment of purchase agreements if acting as principal. Must not perform brokerage acts or collect commission without a DRE license.",
    recommendedStrategy: "Equitable Interest Disclosure",
    earnestMoneyStandard: "$500 - $2,500 Typical",
    penaltiesSummary: "DRE Cease and Desist orders and civil liability.",
    compliantClauses: [
      "Clear disclosure of wholesale assignment fee as contractual consideration, not brokerage commission.",
    ],
  },
};

export const LIVE_REAL_ESTATE_NEWS: MarketNewsTicker[] = [
  {
    id: "news-1",
    headline: "2026 Wholesale Regulation Roundup: 5 States Tighten Equitable Interest Rules",
    category: "REGULATORY",
    timestamp: "12 mins ago",
    impact: "CRITICAL",
    summary: "Oklahoma and Illinois enforce strict double-closing requirements for non-licensed wholesalers. Texas and Arizona mandate clear statutory disclosure of equitable interest.",
  },
  {
    id: "news-2",
    headline: "Federal Reserve Holds Benchmark Rate: Institutional Cash Inflows into Distressed Housing",
    category: "INTEREST_RATES",
    timestamp: "1 hour ago",
    impact: "HIGH",
    summary: "Stable rates fuel aggressive cash buyer buy-box appetites in Midwest and Sunbelt single-family portfolios under $75,000.",
  },
  {
    id: "news-3",
    headline: "Midwest Single Family Inventory: Detroit, Cleveland & Memphis Lead Nationwide ROI",
    category: "DISTRESSED_INVENTORY",
    state: "MI",
    timestamp: "3 hours ago",
    impact: "HIGH",
    summary: "Wayne County MI and Shelby County TN record highest average wholesale spreads, averaging $24,800 projected gross profit on sub-$50k properties.",
  },
  {
    id: "news-4",
    headline: "Title & Escrow Tech: Remote Online Notarization (RON) Now Accepted in 45 States",
    category: "WHOLESALE_UPDATE",
    timestamp: "5 hours ago",
    impact: "INFO",
    summary: "Virtual contracting desks accelerate 7-day cash closes without requiring physical seller attendance at closing tables.",
  },
  {
    id: "news-5",
    headline: "$0 Down Purchase Contracts: Appellate Precedent Affirms Valid Mutual Consideration",
    category: "REGULATORY",
    timestamp: "8 hours ago",
    impact: "HIGH",
    summary: "Legal consensus confirms promissory consideration (obligation to perform due diligence) satisfies contract formation without mandatory cash earnest money.",
  },
];

export function getStateWholesaleInfo(stateCode: string): StateWholesaleRule {
  const code = stateCode.toUpperCase().trim();
  if (STATE_WHOLESALE_RULES[code]) {
    return STATE_WHOLESALE_RULES[code];
  }

  // Default fallback for other US states
  return {
    stateCode: code,
    stateName: code,
    licenseStatus: "DIRECT_ASSIGNMENT_ALLOWED",
    badgeLabel: "Direct Assignment Allowed",
    badgeColor: "emerald",
    statute: "U.S. Common Law Contract Assignment Doctrine",
    summary: `${code} allows assignment of purchase and sale agreements by principals holding equitable interest. Clear disclosures recommended.`,
    recommendedStrategy: "Standard Assignment",
    earnestMoneyStandard: "Optional / $0",
    penaltiesSummary: "Standard civil contract rules apply.",
    compliantClauses: [
      "Buyer reserves the full right to assign this agreement to any designated third party.",
      "Earnest money is negotiable and optional upon mutual agreement of Buyer and Seller.",
    ],
  };
}
