import {
  Property,
  Deal,
  Contact,
  OutreachMessage,
  Investor,
  SearchProfile,
  ProfitSnapshot,
  ContractDraft,
  ApprovalRequest,
  RealizedDealData,
  SellerRecord,
  BuyerRecord,
  PropertyInspection,
} from "../types";
import { calculateDealProfit, calculateDealScore, getRecommendation } from "./profitEngine";

export const INITIAL_SEARCH_PROFILES: SearchProfile[] = [
  {
    id: "sp-1",
    name: "Deep Discount Cash Flow (Under $50k)",
    country: "US",
    states: ["MI", "TN", "OH", "MD", "AL", "IN", "MO"],
    maxPrice: 50000,
    minProfit: 20000,
    minROI: 25,
    propertyTypes: ["single_family", "multifamily"],
    minBedrooms: 2,
    minSquareFeet: 800,
    maxDaysOnMarket: 90,
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "sp-2",
    name: "Midwest BRRRR Targets",
    country: "US",
    states: ["OH", "IN", "MI"],
    maxPrice: 75000,
    minProfit: 25000,
    minROI: 30,
    propertyTypes: ["single_family", "condo"],
    minBedrooms: 3,
    minSquareFeet: 1000,
    maxDaysOnMarket: 60,
    createdAt: "2026-08-18T14:30:00Z",
  },
  {
    id: "sp-3",
    name: "Southeast Wholesale Quick-Flips",
    country: "US",
    states: ["TN", "AL", "GA", "NC"],
    maxPrice: 65000,
    minProfit: 18000,
    minROI: 22,
    propertyTypes: ["single_family", "townhouse"],
    minBedrooms: 2,
    minSquareFeet: 900,
    maxDaysOnMarket: 45,
    createdAt: "2026-08-19T09:15:00Z",
  },
  {
    id: "sp-4",
    name: "Vacant Land & Infill Parcels (Up to $500k)",
    country: "US",
    states: ["TX", "FL", "AZ", "TN", "OK", "MI", "AL"],
    maxPrice: 500000,
    minProfit: 30000,
    minROI: 25,
    propertyTypes: ["land"],
    minBedrooms: 0,
    minSquareFeet: 0,
    maxDaysOnMarket: 120,
    createdAt: "2026-08-20T10:00:00Z",
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: "prop-1",
    address: "742 Oak Street",
    city: "Detroit",
    state: "MI",
    zip: "48202",
    county: "Wayne County",
    parcelId: "01004829.001",
    propertyType: "single_family",
    bedrooms: 3,
    bathrooms: 1.5,
    sqft: 1350,
    yearBuilt: 1948,
    askingPrice: 38000,
    estimatedValue: 95000,
    estimatedRepairs: 14000,
    expectedSalePrice: 92000,
    daysOnMarket: 34,
    source: "MLS Direct Feed",
    sourceUrl: "https://realestate-data.us/detroit/742-oak",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    latitude: 42.3688,
    longitude: -83.0722,
    listingAgent: {
      name: "Marcus Vance",
      agency: "Great Lakes Realty Group",
      phone: "(313) 555-0194",
      email: "marcus.vance@greatlakesrealty.com",
      verified: true,
    },
    comps: [
      { address: "758 Oak St, Detroit, MI", salePrice: 94500, sqft: 1380, distanceMiles: 0.1, soldDate: "2026-07-12", similarityScore: 94 },
      { address: "715 Elm Ave, Detroit, MI", salePrice: 89000, sqft: 1300, distanceMiles: 0.3, soldDate: "2026-06-28", similarityScore: 88 },
      { address: "812 Pine St, Detroit, MI", salePrice: 96000, sqft: 1420, distanceMiles: 0.4, soldDate: "2026-08-01", similarityScore: 91 },
    ],
    description: "Solid brick colonial in revitalization corridor. Roof replaced in 2021. Requires cosmetic interior renovation, kitchen cabinet update, and bathroom overhaul. High rental demand from nearby medical campus.",
    createdAt: "2026-08-19T08:00:00Z",
    updatedAt: "2026-08-20T12:00:00Z",
  },
  {
    id: "prop-2",
    address: "1845 Lamar Avenue",
    city: "Memphis",
    state: "TN",
    zip: "38114",
    county: "Shelby County",
    parcelId: "043088-00012",
    propertyType: "single_family",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1420,
    yearBuilt: 1955,
    askingPrice: 44000,
    estimatedValue: 105000,
    estimatedRepairs: 18000,
    expectedSalePrice: 102000,
    daysOnMarket: 22,
    source: "Wholesale Partner Network",
    sourceUrl: "https://mid-south-deals.com/1845-lamar",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    latitude: 35.1158,
    longitude: -89.9922,
    listingAgent: {
      name: "Tasha Holloway",
      agency: "Bluff City Commercial & Res",
      phone: "(901) 555-8823",
      email: "tasha@bluffcityproperties.com",
      verified: true,
    },
    comps: [
      { address: "1890 Lamar Ave, Memphis, TN", salePrice: 108000, sqft: 1450, distanceMiles: 0.1, soldDate: "2026-07-20", similarityScore: 95 },
      { address: "1760 Nelson Ave, Memphis, TN", salePrice: 99000, sqft: 1390, distanceMiles: 0.4, soldDate: "2026-08-04", similarityScore: 89 },
    ],
    description: "Motivated seller relocation. Hardwood floors under carpet, central HVAC functional but dated, exterior painting and drywall patch needed. Strong cash flow comp market with $1,150/mo potential rent.",
    createdAt: "2026-08-19T09:30:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
  },
  {
    id: "prop-3",
    address: "3210 E 118th Street",
    city: "Cleveland",
    state: "OH",
    zip: "44120",
    county: "Cuyahoga County",
    parcelId: "128-15-042",
    propertyType: "multifamily",
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1840,
    yearBuilt: 1928,
    askingPrice: 48000,
    estimatedValue: 118000,
    estimatedRepairs: 22000,
    expectedSalePrice: 115000,
    daysOnMarket: 49,
    source: "County Tax Lien Registry",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80",
    latitude: 41.4878,
    longitude: -81.5977,
    listingAgent: {
      name: "David Kormos",
      agency: "Buckeye Heritage Realty",
      phone: "(216) 555-4309",
      email: "dkormos@buckeyerealty.com",
      verified: true,
    },
    comps: [
      { address: "3185 E 116th St, Cleveland, OH", salePrice: 116000, sqft: 1800, distanceMiles: 0.2, soldDate: "2026-07-30", similarityScore: 92 },
      { address: "3302 E 120th St, Cleveland, OH", salePrice: 119500, sqft: 1900, distanceMiles: 0.3, soldDate: "2026-06-15", similarityScore: 90 },
    ],
    description: "Turnkey duplex opportunity (2 bed / 1 bath each unit). Lower unit occupied on MTM lease. Upper unit vacant needing new flooring and bathroom vanity. Projected total rent $1,600/month.",
    createdAt: "2026-08-18T16:00:00Z",
    updatedAt: "2026-08-20T10:15:00Z",
  },
  {
    id: "prop-4",
    address: "2412 E Preston Street",
    city: "Baltimore",
    state: "MD",
    zip: "21213",
    county: "Baltimore City",
    parcelId: "08-14-1422-019",
    propertyType: "townhouse",
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1120,
    yearBuilt: 1920,
    askingPrice: 32000,
    estimatedValue: 85000,
    estimatedRepairs: 19000,
    expectedSalePrice: 82000,
    daysOnMarket: 61,
    source: "Bank REO Dispositions",
    status: "ANALYZING",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    latitude: 39.3065,
    longitude: -76.5824,
    listingAgent: {
      name: "Cheryl Jenkins",
      agency: "Chesapeake Asset Management",
      phone: "(410) 555-7712",
      email: "cjenkins@chesapeakereos.com",
      verified: true,
    },
    comps: [
      { address: "2420 E Preston St, Baltimore, MD", salePrice: 84000, sqft: 1150, distanceMiles: 0.05, soldDate: "2026-08-02", similarityScore: 96 },
      { address: "2350 E Biddle St, Baltimore, MD", salePrice: 79000, sqft: 1100, distanceMiles: 0.3, soldDate: "2026-07-10", similarityScore: 87 },
    ],
    description: "Classic Baltimore rowhome. Solid exterior shell and foundation. Needs complete mechanical and finish overhaul. Johns Hopkins hospital shuttle corridor.",
    createdAt: "2026-08-19T11:00:00Z",
    updatedAt: "2026-08-20T08:00:00Z",
  },
  {
    id: "prop-5",
    address: "914 14th Street SW",
    city: "Birmingham",
    state: "AL",
    zip: "35211",
    county: "Jefferson County",
    parcelId: "29-00-14-3-002-018",
    propertyType: "single_family",
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1210,
    yearBuilt: 1952,
    askingPrice: 35000,
    estimatedValue: 88000,
    estimatedRepairs: 12500,
    expectedSalePrice: 86000,
    daysOnMarket: 18,
    source: "Direct Mail Campaign",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=800&q=80",
    latitude: 33.4862,
    longitude: -86.8488,
    listingAgent: {
      name: "Greg Sterling",
      agency: "Magic City Acquisitions",
      phone: "(205) 555-9321",
      email: "greg@magiccityacq.com",
      verified: true,
    },
    comps: [
      { address: "930 14th St SW, Birmingham, AL", salePrice: 87500, sqft: 1250, distanceMiles: 0.1, soldDate: "2026-08-11", similarityScore: 95 },
      { address: "1012 Cotton Ave SW, Birmingham, AL", salePrice: 83000, sqft: 1180, distanceMiles: 0.4, soldDate: "2026-07-25", similarityScore: 89 },
    ],
    description: "Charming West End bungalow. Roof in fair condition (8 yrs old). Needs HVAC compressor replacement, interior paint, vinyl plank flooring, and light landscaping.",
    createdAt: "2026-08-20T06:00:00Z",
    updatedAt: "2026-08-20T13:00:00Z",
  },
  {
    id: "prop-6",
    address: "4118 Natural Bridge Avenue",
    city: "St. Louis",
    state: "MO",
    zip: "63115",
    county: "St. Louis City",
    parcelId: "4429-00-0210",
    propertyType: "single_family",
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1650,
    yearBuilt: 1935,
    askingPrice: 42000,
    estimatedValue: 98000,
    estimatedRepairs: 16000,
    expectedSalePrice: 95000,
    daysOnMarket: 41,
    source: "MLS Direct Feed",
    status: "DISCOVERED",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    latitude: 38.6651,
    longitude: -90.2312,
    listingAgent: {
      name: "Alicia Moreau",
      agency: "Gateway Premier Properties",
      phone: "(314) 555-6677",
      email: "amoreau@gatewaypremier.com",
      verified: true,
    },
    comps: [
      { address: "4150 Natural Bridge Ave, St. Louis, MO", salePrice: 96000, sqft: 1680, distanceMiles: 0.1, soldDate: "2026-07-18", similarityScore: 93 },
    ],
    description: "Spacious 2-story brick single family. New vinyl windows, updated electrical panel. Kitchen and bath require modern finishes.",
    createdAt: "2026-08-20T07:30:00Z",
    updatedAt: "2026-08-20T07:30:00Z",
  },
  {
    id: "prop-7",
    address: "2835 N Delaware Street",
    city: "Indianapolis",
    state: "IN",
    zip: "46205",
    county: "Marion County",
    parcelId: "49-06-25-118-004.000-101",
    propertyType: "single_family",
    bedrooms: 3,
    bathrooms: 1.5,
    sqft: 1480,
    yearBuilt: 1940,
    askingPrice: 49000,
    estimatedValue: 112000,
    estimatedRepairs: 15500,
    expectedSalePrice: 108000,
    daysOnMarket: 14,
    source: "Pre-Foreclosure Registry",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=80",
    latitude: 39.8082,
    longitude: -86.1534,
    listingAgent: {
      name: "Bradley Cooper",
      agency: "Hoosier Valley Realty",
      phone: "(317) 555-8291",
      email: "bcooper@hoosieryvalley.com",
      verified: true,
    },
    comps: [
      { address: "2810 N Delaware St, Indianapolis, IN", salePrice: 111000, sqft: 1500, distanceMiles: 0.05, soldDate: "2026-08-08", similarityScore: 97 },
      { address: "2904 N Pennsylvania St, Indianapolis, IN", salePrice: 115000, sqft: 1540, distanceMiles: 0.2, soldDate: "2026-07-22", similarityScore: 92 },
    ],
    description: "Rapidly appreciating Mapleton-Fall Creek submarket. Solid mechanics. Needs kitchen refresh, bathroom vanity, and hardwood floor refinishing.",
    createdAt: "2026-08-19T14:00:00Z",
    updatedAt: "2026-08-20T11:45:00Z",
  },
  {
    id: "prop-8",
    address: "156 Campbell Park",
    city: "Rochester",
    state: "NY",
    zip: "14606",
    county: "Monroe County",
    parcelId: "105.74-2-19",
    propertyType: "single_family",
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1180,
    yearBuilt: 1930,
    askingPrice: 36000,
    estimatedValue: 86000,
    estimatedRepairs: 13000,
    expectedSalePrice: 84000,
    daysOnMarket: 29,
    source: "MLS Direct Feed",
    status: "DISCOVERED",
    imageUrl: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=800&q=80",
    latitude: 43.1610,
    longitude: -77.6540,
    listingAgent: {
      name: "Helena Ross",
      agency: "Genesee River Properties",
      phone: "(585) 555-3120",
      email: "helena@geneseeriver.com",
      verified: true,
    },
    comps: [
      { address: "142 Campbell Park, Rochester, NY", salePrice: 85000, sqft: 1200, distanceMiles: 0.05, soldDate: "2026-07-15", similarityScore: 94 },
    ],
    description: "Affordable cashflow rental market. Clean structural bones. Needs roof tune-up, new hot water tank, and cosmetic updates.",
    createdAt: "2026-08-20T05:00:00Z",
    updatedAt: "2026-08-20T05:00:00Z",
  },
  {
    id: "prop-9",
    address: "Lot 14-18 Pine Creek Ranch Road",
    city: "Austin",
    state: "TX",
    zip: "78738",
    county: "Travis County",
    parcelId: "013400-0922",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 631620,
    lotSizeAcres: 14.5,
    zoning: "Rural Residential / Subdividable",
    roadAccess: "Paved County Road Frontage (420 ft)",
    utilitiesAvailable: "Electric at Road, Well & Septic Permitted",
    askingPrice: 340000,
    estimatedValue: 560000,
    estimatedRepairs: 25000,
    expectedSalePrice: 540000,
    daysOnMarket: 19,
    source: "Texas Rural Land Network",
    sourceUrl: "https://texas-land-acq.com/pine-creek-ranch",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
    latitude: 30.3421,
    longitude: -97.9892,
    listingAgent: {
      name: "Caleb Sterling",
      agency: "Lone Star Land & Ranch Realty",
      phone: "(512) 555-9011",
      email: "caleb@lonestarlandrealty.com",
      verified: true,
    },
    comps: [
      { address: "Tract 12 Pine Creek Rd, Austin, TX", salePrice: 545000, sqft: 609840, distanceMiles: 0.3, soldDate: "2026-07-28", similarityScore: 95 },
      { address: "Lot 22 Barton Creek Canyon, Austin, TX", salePrice: 575000, sqft: 653400, distanceMiles: 0.8, soldDate: "2026-06-19", similarityScore: 91 },
    ],
    description: "Prime 14.5-acre Hill Country development tract. Rolling topography, mature live oaks, gentle building sites with canyon views. Pre-approved for 4-lot minor subdivision or luxury private equestrian estate.",
    createdAt: "2026-08-20T08:00:00Z",
    updatedAt: "2026-08-20T12:30:00Z",
  },
  {
    id: "prop-10",
    address: "2204 N 24th Street",
    city: "Tampa",
    state: "FL",
    zip: "33605",
    county: "Hillsborough County",
    parcelId: "A-18-29-19-4X9-000002-00014.0",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 15246,
    lotSizeAcres: 0.35,
    zoning: "RS-50 Single/Multi-Family Infill",
    roadAccess: "City Paved Street Curb & Gutter",
    utilitiesAvailable: "Municipal Water, Sewer, Power at Curb",
    askingPrice: 68000,
    estimatedValue: 150000,
    estimatedRepairs: 6000,
    expectedSalePrice: 145000,
    daysOnMarket: 12,
    source: "Hillsborough County Tax Lien Dispositions",
    sourceUrl: "https://tampa-parcels.gov/2204-n-24th",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80",
    latitude: 27.9620,
    longitude: -82.4330,
    listingAgent: {
      name: "Elena Vasquez",
      agency: "Gulf Coast Land Assets",
      phone: "(813) 555-6320",
      email: "elena@gulfcoastlandassets.com",
      verified: true,
    },
    comps: [
      { address: "2218 N 24th St, Tampa, FL", salePrice: 142000, sqft: 14800, distanceMiles: 0.05, soldDate: "2026-08-05", similarityScore: 96 },
      { address: "2109 E 22nd Ave, Tampa, FL", salePrice: 155000, sqft: 16000, distanceMiles: 0.2, soldDate: "2026-07-14", similarityScore: 92 },
    ],
    description: "Shovel-ready builder infill lot in rapid Ybor City revitalization corridor. Zero wetlands, impact fee credits available. Survey completed and clean title verified.",
    createdAt: "2026-08-20T09:15:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
  },
  {
    id: "prop-11",
    address: "8920 E Sonoran Vista Parkway",
    city: "Scottsdale",
    state: "AZ",
    zip: "85262",
    county: "Maricopa County",
    parcelId: "216-72-014C",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 226512,
    lotSizeAcres: 5.2,
    zoning: "R-190 Custom Luxury Homesite / Equestrian",
    roadAccess: "Paved Road Frontage with Culvert",
    utilitiesAvailable: "Electric, City Water Meter Box Installed",
    askingPrice: 465000,
    estimatedValue: 720000,
    estimatedRepairs: 18000,
    expectedSalePrice: 690000,
    daysOnMarket: 25,
    source: "Maricopa Probate & Estate Dispositions",
    sourceUrl: "https://desert-land-hub.com/sonoran-vista-8920",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    latitude: 33.7289,
    longitude: -111.8845,
    listingAgent: {
      name: "Darren Montgomery",
      agency: "Desert Luxury Land Partners",
      phone: "(480) 555-4491",
      email: "darren@desertluxuryland.com",
      verified: true,
    },
    comps: [
      { address: "8960 E Sonoran Vista Pkwy, Scottsdale, AZ", salePrice: 710000, sqft: 217800, distanceMiles: 0.1, soldDate: "2026-07-19", similarityScore: 97 },
      { address: "9102 E Pinnacle Peak Rd, Scottsdale, AZ", salePrice: 745000, sqft: 240000, distanceMiles: 0.6, soldDate: "2026-06-30", similarityScore: 90 },
    ],
    description: "Spectacular 5.2-acre pristine high-desert custom homesite backing to McDowell Sonoran Preserve. 360-degree mountain & city light vistas. Massive spread for luxury spec builder or land wholesaler.",
    createdAt: "2026-08-19T15:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "prop-12",
    address: "Tract 9 Cumberland Ridge Road",
    city: "Crossville",
    state: "TN",
    zip: "38555",
    county: "Cumberland County",
    parcelId: "099-041.02",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 1219680,
    lotSizeAcres: 28.0,
    zoning: "Unrestricted Agricultural / Recreational / Subdivision",
    roadAccess: "650 ft State Highway Access",
    utilitiesAvailable: "Municipal Water & Fiber at Road",
    askingPrice: 120000,
    estimatedValue: 235000,
    estimatedRepairs: 8000,
    expectedSalePrice: 225000,
    daysOnMarket: 31,
    source: "Tennessee Forestry & Timber Liquidation",
    sourceUrl: "https://cumberland-land-sales.com/tract-9",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    latitude: 35.9520,
    longitude: -85.0289,
    listingAgent: {
      name: "Hoyt Sterling",
      agency: "Cumberland Plateau Realty",
      phone: "(931) 555-8910",
      email: "hoyt@cumberlandplateau.com",
      verified: true,
    },
    comps: [
      { address: "Tract 4 Cumberland Ridge Rd, Crossville, TN", salePrice: 220000, sqft: 1150000, distanceMiles: 0.4, soldDate: "2026-08-01", similarityScore: 94 },
    ],
    description: "28 acres of high-plateau hardwood timberland with seasonal stream and ridge views. Unrestricted zoning permits tiny home community, RV glamping resort, or 5-acre subdividing.",
    createdAt: "2026-08-20T04:00:00Z",
    updatedAt: "2026-08-20T04:00:00Z",
  },
  {
    id: "prop-13",
    address: "4410 NW 39th Expressway",
    city: "Oklahoma City",
    state: "OK",
    zip: "73112",
    county: "Oklahoma County",
    parcelId: "R128893100",
    propertyType: "land",
    bedrooms: 0,
    bathrooms: 0,
    sqft: 121968,
    lotSizeAcres: 2.8,
    zoning: "C-3 General Commercial / Light Industrial / Flex Infill",
    roadAccess: "Highway Commercial Frontage & Curb Cuts",
    utilitiesAvailable: "City Water, Heavy 3-Phase Power, Gas, Sewer",
    askingPrice: 185000,
    estimatedValue: 325000,
    estimatedRepairs: 12000,
    expectedSalePrice: 310000,
    daysOnMarket: 17,
    source: "Oklahoma Bank Commercial REO",
    sourceUrl: "https://okc-commercial-assets.com/4410-nw-39th",
    status: "QUALIFIED",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80",
    latitude: 35.5110,
    longitude: -97.5990,
    listingAgent: {
      name: "Wayne Callahan",
      agency: "Sooner Commercial & Land",
      phone: "(405) 555-7301",
      email: "wayne@soonercommercial.com",
      verified: true,
    },
    comps: [
      { address: "4490 NW 39th Expy, Oklahoma City, OK", salePrice: 315000, sqft: 120000, distanceMiles: 0.1, soldDate: "2026-07-11", similarityScore: 96 },
    ],
    description: "High-traffic commercial frontage acreage. Direct access to Interstate corridor. Ideal for boat/RV self-storage, contractor yard, or fleet logistics.",
    createdAt: "2026-08-19T12:00:00Z",
    updatedAt: "2026-08-20T09:30:00Z",
  },
];

export function generateInitialDeals(): Deal[] {
  return INITIAL_PROPERTIES.map((prop) => {
    const purchasePrice = prop.askingPrice;
    const repairs = prop.estimatedRepairs;
    const closingCosts = Math.round(purchasePrice * 0.035);
    const holdingCosts = 1800;
    const financingCosts = 1200;
    const taxes = 950;
    const insurance = 650;
    const utilities = 400;
    const otherCosts = 500;

    const expectedSalePrice = prop.expectedSalePrice;
    const sellingCosts = Math.round(expectedSalePrice * 0.03);
    const commissions = Math.round(expectedSalePrice * 0.05);
    const concessions = 0;

    const dealInput = {
      purchasePrice,
      repairs,
      closingCosts,
      holdingCosts,
      financingCosts,
      taxes,
      insurance,
      utilities,
      otherCosts,
      expectedSalePrice,
      sellingCosts,
      commissions,
      concessions,
    };

    const metrics = calculateDealProfit(dealInput);

    const discountRate = Math.round(((expectedSalePrice - purchasePrice) / expectedSalePrice) * 100);
    const scoreInput = {
      financialOpportunity: Math.min(100, Math.round((metrics.projectedProfit / 25000) * 100)),
      discount: Math.min(100, discountRate * 1.5),
      compsConfidence: prop.comps && prop.comps.length > 0 ? 88 : 65,
      repairConfidence: 82,
      marketLiquidity: 80,
      exitPotential: 85,
      daysOnMarket: Math.max(30, 100 - prop.daysOnMarket),
      dataConfidence: 90,
    };

    const dealScore = calculateDealScore(scoreInput);
    const recommendation = getRecommendation(dealScore, metrics.projectedProfit, metrics.roi);

    let stage: Deal["status"] = "ANALYSIS";
    if (prop.status === "QUALIFIED") stage = "OFFER";
    if (prop.id === "prop-1") stage = "NEGOTIATION";
    if (prop.id === "prop-2") stage = "OFFER";

    const verifiedFacts =
      prop.propertyType === "land"
        ? [
            `Asking price verified at $${purchasePrice.toLocaleString()} via county land registry feed`,
            `Acreage recorded at ${prop.lotSizeAcres || (prop.sqft / 43560).toFixed(2)} acres (${prop.sqft.toLocaleString()} sqft) in county GIS`,
            `Zoning verified: ${prop.zoning || "Residential / Infill Development"} with legal road frontage`,
            `Title report checked: Clean parcel record with fee simple ownership and zero unrecorded easements`,
          ]
        : [
            `Asking price verified at $${purchasePrice.toLocaleString()} via MLS direct feed`,
            `Square footage recorded at ${prop.sqft} sqft from county tax assessor`,
            `${prop.comps?.length || 0} recent comparable sales verified within 0.5 miles`,
            `Title report checked: Clean parcel record with no municipal stop-work orders`,
          ];

    const estimates =
      prop.propertyType === "land"
        ? [
            `Estimated site prep & entitlement buffer: $${repairs.toLocaleString()}`,
            `Holding costs modeled at 3-4 months closing window ($${holdingCosts})`,
            `Resale / Dispo value projected at $${expectedSalePrice.toLocaleString()} based on submarket acreage comps`,
          ]
        : [
            `Estimated repairs of $${repairs.toLocaleString()} based on regional cosmetic labor index`,
            `Holding costs modeled at 4 months turnover cycle ($${holdingCosts})`,
            `Resale ARV projected at $${expectedSalePrice.toLocaleString()} based on adjusted comps`,
          ];

    const unknowns =
      prop.propertyType === "land"
        ? [
            "Soil percolation & environmental Phase 1 verification recommended",
            "Topographical boundary survey pin physical confirmation pending",
          ]
        : [
            "Sewer lateral condition pending camera inspection",
            "HVAC heat exchanger age requires physical mechanical tag verification",
          ];

    const risks =
      prop.propertyType === "land"
        ? [
            "Municipal tap fees and setback variance verification recommended",
            "Wetland delineation and flood zone map verification recommended prior to disposition",
          ]
        : [
            "Repair contingency allowance recommended +15% for unforeseen drywall issues",
            "Local municipal occupancy permit required prior to tenant move-in",
          ];

    const nextAction =
      recommendation === "PURSUE"
        ? prop.propertyType === "land"
          ? `Issue Land LOI cash offer at $${Math.round(purchasePrice * 0.9).toLocaleString()} with 14-day feasibility study`
          : `Submit LOI offer at $${Math.round(purchasePrice * 0.95).toLocaleString()} cash with 7-day inspection window`
        : "Review contractor scope and request listing agent disclosure pack";

    return {
      id: `deal-${prop.id.replace("prop-", "")}`,
      propertyId: prop.id,
      property: prop,
      financials: dealInput,
      metrics,
      dealScore,
      confidence: 84,
      recommendation,
      status: stage,
      verifiedFacts,
      estimates,
      unknowns,
      risks,
      nextAction,
      createdAt: prop.createdAt,
      updatedAt: prop.updatedAt,
    };
  });
}

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: "cont-1",
    name: "Marcus Vance",
    company: "Great Lakes Realty Group",
    role: "LISTING_AGENT",
    phone: "(313) 555-0194",
    email: "marcus.vance@greatlakesrealty.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "MLS Direct Feed",
    source_url: "https://realestate-data.us/detroit/742-oak",
    sourceUrl: "https://realestate-data.us/detroit/742-oak",
    sourceCategory: "PUBLIC_LISTING",
    status: "NEGOTIATING",
    notes: "Very responsive. Handles multiple Wayne County bank portfolios.",
    lastContactedAt: "2026-08-20T10:30:00Z",
    lastNotesUpdate: "2026-08-20T10:30:00Z",
    propertiesAssociated: ["prop-1"],
  },
  {
    id: "cont-2",
    name: "Tasha Holloway",
    company: "Bluff City Commercial & Res",
    role: "LISTING_AGENT",
    phone: "(901) 555-8823",
    email: "tasha@bluffcityproperties.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "Wholesale Partner Network",
    source_url: "https://mid-south-deals.com/1845-lamar",
    sourceUrl: "https://mid-south-deals.com/1845-lamar",
    sourceCategory: "PUBLIC_LISTING",
    status: "CONTACTED",
    notes: "Prefers cash offers with quick 10-day closings.",
    lastContactedAt: "2026-08-19T14:20:00Z",
    lastNotesUpdate: "2026-08-19T14:20:00Z",
    propertiesAssociated: ["prop-2"],
  },
  {
    id: "cont-seller-1",
    name: "Karen Whitfield",
    company: "Whitfield Family Trust",
    role: "PROPERTY_OWNER",
    phone: "(931) 555-4819",
    email: "karen.whitfield@gmail.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "LandWatch",
    source_url: "https://www.landwatch.com",
    sourceUrl: "https://www.landwatch.com",
    sourceCategory: "PUBLIC_LISTING",
    status: "NEGOTIATING",
    fitReason: "Found via LandWatch listing search. Motivated seller with 28 unrestricted timber acres.",
    notes: "Inherited Cumberland plateau acreage. Open to $105,000 cash for rapid 14-day close.",
    lastContactedAt: "2026-08-20T08:00:00Z",
    lastNotesUpdate: "2026-08-20T08:00:00Z",
    propertiesAssociated: ["prop-12"],
  },
  {
    id: "cont-seller-2",
    name: "Tom Reyes",
    company: "Reyes Cattle & Land LP",
    role: "PROPERTY_OWNER",
    phone: "(512) 555-2940",
    email: "tom.reyes@reyesranches.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "Land And Farm",
    source_url: "https://www.landandfarm.com",
    sourceUrl: "https://www.landandfarm.com",
    sourceCategory: "PUBLIC_LISTING",
    status: "CONTACTED",
    fitReason: "Found via Land And Farm listing search. Motivated ranch liquidation, 14.5 acres in Blanco County.",
    notes: "Has 14.5 acre parcel in Texas Hill Country with live oak trees and AG exemption. Seeking clean cash buyer.",
    lastContactedAt: "2026-08-16T10:00:00Z",
    lastNotesUpdate: "2026-08-16T10:00:00Z",
    propertiesAssociated: ["prop-9"],
  },
  {
    id: "cont-seller-3",
    name: "Delores Nguyen",
    company: "Private Landowner",
    role: "PROPERTY_OWNER",
    phone: "(480) 555-7728",
    email: "delores.nguyen@outlook.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "County Assessor (Delinquent Tax)",
    source_url: "https://mcassessor.maricopa.gov",
    sourceUrl: "https://mcassessor.maricopa.gov",
    sourceCategory: "OFF_MARKET_TAX",
    status: "NEW",
    fitReason: "Found via Maricopa County Assessor delinquent tax records. 5.2-acre Scottsdale luxury homesite with $4,200 back taxes.",
    notes: "Out-of-state heir with 5.2 custom acres near McDowell Preserve. Wants to avoid tax auction.",
    lastContactedAt: "2026-08-15T09:00:00Z",
    lastNotesUpdate: "2026-08-15T09:00:00Z",
    propertiesAssociated: ["prop-11"],
  },
  {
    id: "cont-3",
    name: "David Kormos",
    company: "Buckeye Heritage Realty",
    role: "LISTING_AGENT",
    phone: "(216) 555-4309",
    email: "dkormos@buckeyerealty.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "MLS Direct Feed",
    source_url: "https://realestate-data.us/cleveland/3210-e118",
    sourceUrl: "https://realestate-data.us/cleveland/3210-e118",
    sourceCategory: "PUBLIC_LISTING",
    status: "NEW",
    notes: "Specializes in Cuyahoga multi-families.",
    lastContactedAt: "2026-08-14T11:00:00Z",
    lastNotesUpdate: "2026-08-14T11:00:00Z",
    propertiesAssociated: ["prop-3"],
  },
  {
    id: "cont-6",
    name: "Caleb Sterling",
    company: "Lone Star Land & Ranch Realty",
    role: "BROKER",
    phone: "(512) 555-9011",
    email: "caleb@lonestarlandrealty.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "Lands of America",
    source_url: "https://www.landsofamerica.com",
    sourceUrl: "https://www.landsofamerica.com",
    sourceCategory: "PUBLIC_LISTING",
    status: "NEGOTIATING",
    notes: "Specializes in Hill Country & Central Texas acreage, raw land, and builder subdivisions.",
    lastContactedAt: "2026-08-20T11:00:00Z",
    lastNotesUpdate: "2026-08-20T11:00:00Z",
    propertiesAssociated: ["prop-9"],
  },
  {
    id: "cont-7",
    name: "Elena Vasquez",
    company: "Gulf Coast Land Assets",
    role: "LISTING_AGENT",
    phone: "(813) 555-6320",
    email: "elena@gulfcoastlandassets.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "PropStream Off-Market Filter",
    source_url: "https://www.propstream.com",
    sourceUrl: "https://www.propstream.com",
    sourceCategory: "OFF_MARKET_TAX",
    status: "CONTACTED",
    notes: "Direct contact for Florida infill builder parcels and probate vacant lots.",
    lastContactedAt: "2026-08-19T15:00:00Z",
    lastNotesUpdate: "2026-08-19T15:00:00Z",
    propertiesAssociated: ["prop-10"],
  },
  {
    id: "cont-8",
    name: "Darren Montgomery",
    company: "Desert Luxury Land Partners",
    role: "LISTING_AGENT",
    phone: "(480) 555-4491",
    email: "darren@desertluxuryland.com",
    emailVerified: true,
    doNotContact: false,
    unsubscribed: false,
    source: "Maricopa County Probate Feed",
    source_url: "https://mcassessor.maricopa.gov",
    sourceUrl: "https://mcassessor.maricopa.gov",
    sourceCategory: "PROBATE",
    status: "NEGOTIATING",
    notes: "Scottsdale and Maricopa luxury parcel acquisitions and spec homesite syndication.",
    lastContactedAt: "2026-08-20T09:30:00Z",
    lastNotesUpdate: "2026-08-20T09:30:00Z",
    propertiesAssociated: ["prop-11"],
  },
];

export const INITIAL_OUTREACH_MESSAGES: OutreachMessage[] = [
  {
    id: "out-1",
    contactId: "cont-1",
    contactName: "Marcus Vance",
    contactEmail: "marcus.vance@greatlakesrealty.com",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI",
    channel: "EMAIL",
    subject: "Cash Offer Inquiry - 742 Oak Street, Detroit",
    body: `Hi Marcus,\n\nI hope you're having a great week. I represent an active cash buyer group currently expanding our portfolio in Detroit.\n\nWe completed our preliminary underwriting on 742 Oak Street. We love the location and are prepared to submit a clean, non-contingent cash offer with zero financing delays and a 10-day close.\n\nCould you confirm if the seller is open to an all-cash agreement at $36,000, and whether disclosures are available for review today?\n\nBest regards,\nDealHunter AI Acquisitions Team`,
    status: "SENT",
    responded: true,
    doNotContact: false,
    sequenceStep: 1,
    scheduledAt: "2026-08-20T09:00:00Z",
    sentAt: "2026-08-20T09:02:00Z",
    respondedAt: "2026-08-20T11:15:00Z",
    replyText: `Thanks for reaching out. The seller is motivated and willing to consider $36,500 if you can close within 14 days and put down $2,500 EMD. Sending disclosures now.`,
    createdAt: "2026-08-20T08:50:00Z",
  },
  {
    id: "out-2",
    contactId: "cont-2",
    contactName: "Tasha Holloway",
    contactEmail: "tasha@bluffcityproperties.com",
    dealId: "deal-2",
    propertyAddress: "1845 Lamar Avenue, Memphis, TN",
    channel: "EMAIL",
    subject: "Direct Inquiry - 1845 Lamar Avenue, Memphis",
    body: `Hello Tasha,\n\nReaching out regarding your listing at 1845 Lamar Ave. Our underwriting model flagged this property as a great fit for our immediate cash acquisition pipeline.\n\nWe can write an offer without appraisal contingencies and provide proof of funds immediately.\n\nAre you available for a quick 5-minute call today to discuss seller timeline?\n\nBest,\nAcquisitions Desk`,
    status: "SENT",
    responded: false,
    doNotContact: false,
    sequenceStep: 1,
    scheduledAt: "2026-08-20T10:00:00Z",
    sentAt: "2026-08-20T10:01:00Z",
    createdAt: "2026-08-20T09:45:00Z",
  },
];

export const INITIAL_INVESTORS: Investor[] = [
  {
    id: "inv-1",
    name: "Apex Capital Partners",
    company: "Apex Real Estate Holdings LLC",
    contactPerson: "Jordan Vance",
    email: "acquisitions@apexreholding.com",
    phone: "(312) 555-7800",
    targetMarkets: ["MI", "OH", "IN"],
    targetStates: ["MI", "OH", "IN"],
    maxPurchasePrice: 85000,
    minROI: 24,
    minProfit: 20000,
    preferredTypes: ["single_family", "multifamily"],
    availableCapital: 450000,
    activeDealsCount: 3,
    buyBoxMatchCount: 4,
    source: "BiggerPockets Cash Buyers Directory",
    source_url: "https://www.biggerpockets.com/forums/48/topics/midwest-cash-buyers",
    sourceUrl: "https://www.biggerpockets.com/forums/48/topics/midwest-cash-buyers",
    sourceCategory: "BIGGERPOCKETS",
    status: "ACTIVE",
    notes: "Top-tier cash buyer for Midwest single & multifamily turnkeys. Welcomes wholesale assignment contracts.",
    lastContactedAt: "2026-08-20T10:00:00Z",
    lastNotesUpdate: "2026-08-20T10:00:00Z",
    isWholesalerReady: true,
    wholesaleTags: ["Wholesaler-Ready", "Assignment Friendly", "High Priority Lead", "Proof of Funds Verified"],
    priority: "HIGH",
    acceptsAssignments: true,
    targetAssignmentFeeRange: "$5,000 - $20,000",
    wholesalerForumNote: "BiggerPockets thread: 'We close in 10 days on clean assignment contracts in Detroit/Cleveland.'",
  },
  {
    id: "inv-2",
    name: "Desert Ridge Builders",
    company: "Desert Ridge Construction & Development LLC",
    contactPerson: "Cody Rasmussen",
    email: "acquisitions@desertridgebuilders.com",
    phone: "(480) 555-9201",
    targetMarkets: ["AZ", "NV", "UT"],
    targetStates: ["AZ", "NV", "UT"],
    maxPurchasePrice: 650000,
    minROI: 20,
    minProfit: 40000,
    preferredTypes: ["land", "single_family"],
    availableCapital: 3200000,
    activeDealsCount: 4,
    buyBoxMatchCount: 5,
    source: "BiggerPockets Cash Buyers Forum",
    source_url: "https://www.biggerpockets.com/forums/39/topics/maricopa-az-cash-buyers-builder-list",
    sourceUrl: "https://www.biggerpockets.com/forums/39/topics/maricopa-az-cash-buyers-builder-list",
    sourceCategory: "BIGGERPOCKETS",
    status: "ACTIVE",
    notes: "Active custom spec builder seeking 1 to 10-acre infill residential parcels in Maricopa and Pinal counties. Wholesaler-ready with quick title turnaround.",
    lastContactedAt: "2026-08-20T11:30:00Z",
    lastNotesUpdate: "2026-08-20T11:30:00Z",
    isWholesalerReady: true,
    wholesaleTags: ["Wholesaler-Ready", "Assignment Friendly", "High Priority Lead", "Proof of Funds Verified"],
    priority: "HIGH",
    acceptsAssignments: true,
    targetAssignmentFeeRange: "$15,000 - $50,000",
    wholesalerForumNote: "Verified Post: 'Paying standard assignment spreads for Scottsdale/Phoenix infill lots.'",
  },
  {
    id: "inv-3",
    name: "Sonoran Land Holdings",
    company: "Sonoran Land Syndicate LLC",
    contactPerson: "Elena Morales",
    email: "deals@sonoranlandholdings.com",
    phone: "(520) 555-3819",
    targetMarkets: ["AZ", "TX", "NM"],
    targetStates: ["AZ", "TX", "NM"],
    maxPurchasePrice: 500000,
    minROI: 25,
    minProfit: 35000,
    preferredTypes: ["land"],
    availableCapital: 1800000,
    activeDealsCount: 2,
    buyBoxMatchCount: 3,
    source: "Facebook Land Wholesalers Network",
    source_url: "https://www.facebook.com/groups/landinvestorssouthwest",
    sourceUrl: "https://www.facebook.com/groups/landinvestorssouthwest",
    sourceCategory: "FACEBOOK_GROUPS",
    status: "ACTIVE",
    notes: "Specializes in high-desert raw acreage and rural subdivide parcels. Fast 7-day closing.",
    lastContactedAt: "2026-08-19T14:10:00Z",
    lastNotesUpdate: "2026-08-19T14:10:00Z",
    isWholesalerReady: true,
    wholesaleTags: ["Wholesaler-Ready", "Assignment Friendly", "Proof of Funds Verified"],
    priority: "HIGH",
    acceptsAssignments: true,
    targetAssignmentFeeRange: "$10,000 - $30,000",
    wholesalerForumNote: "FB REI Group: 'Direct wholesale contract buyer for acreage in AZ and TX.'",
  },
  {
    id: "inv-4",
    name: "Terra Land Syndicate & Infill Fund",
    company: "Terra Capital Partners LLC",
    contactPerson: "Austin Bradley",
    email: "acquisitions@terralandfund.com",
    phone: "(512) 555-4890",
    targetMarkets: ["TX", "FL", "AZ", "TN", "OK"],
    targetStates: ["TX", "FL", "AZ", "TN", "OK"],
    maxPurchasePrice: 500000,
    minROI: 25,
    minProfit: 30000,
    preferredTypes: ["land"],
    availableCapital: 2500000,
    activeDealsCount: 5,
    buyBoxMatchCount: 6,
    source: "Austin REI Wholesalers Syndicate",
    source_url: "https://www.biggerpockets.com/forums/39/topics/austin-tx-cash-buyers-list",
    sourceUrl: "https://www.biggerpockets.com/forums/39/topics/austin-tx-cash-buyers-list",
    sourceCategory: "BIGGERPOCKETS",
    status: "ACTIVE",
    notes: "Aggressive land acquirer for residential subdivision and infill builder pads. Accepts assigned purchase contracts across 5 states.",
    lastContactedAt: "2026-08-18T16:00:00Z",
    lastNotesUpdate: "2026-08-18T16:00:00Z",
    isWholesalerReady: true,
    wholesaleTags: ["Wholesaler-Ready", "Assignment Friendly", "High Priority Lead", "Proof of Funds Verified"],
    priority: "HIGH",
    acceptsAssignments: true,
    targetAssignmentFeeRange: "$20,000 - $60,000",
    wholesalerForumNote: "Forum Post: 'Actively buying assigned contracts in Texas, Florida, and Tennessee.'",
  },
  {
    id: "inv-5",
    name: "Sunbelt Lots & Development Group",
    company: "Sunbelt Land Holdings LLC",
    contactPerson: "Frank Delgado",
    email: "deals@sunbeltlots.com",
    phone: "(480) 555-7120",
    targetMarkets: ["AZ", "FL", "TX", "MI"],
    targetStates: ["AZ", "FL", "TX", "MI"],
    maxPurchasePrice: 480000,
    minROI: 28,
    minProfit: 25000,
    preferredTypes: ["land", "single_family"],
    availableCapital: 1800000,
    activeDealsCount: 3,
    buyBoxMatchCount: 4,
    source: "LandHub Marketplace",
    source_url: "https://www.landhub.com",
    sourceUrl: "https://www.landhub.com",
    sourceCategory: "LANDMODO",
    status: "ACTIVE",
    notes: "Buys subdivided build-ready parcels in Sunbelt growth corridors.",
    lastContactedAt: "2026-08-20T09:00:00Z",
    lastNotesUpdate: "2026-08-20T09:00:00Z",
    isWholesalerReady: false,
    wholesaleTags: [],
    priority: "MEDIUM",
    acceptsAssignments: false,
  },
  {
    id: "inv-6",
    name: "Mid-South Yield Fund",
    company: "MS Yield Capital LLC",
    contactPerson: "Derrick Bell",
    email: "deals@midsouthyield.com",
    phone: "(901) 555-3411",
    targetMarkets: ["TN", "AL", "GA"],
    targetStates: ["TN", "AL", "GA"],
    maxPurchasePrice: 65000,
    minROI: 22,
    minProfit: 18000,
    preferredTypes: ["single_family"],
    availableCapital: 320000,
    activeDealsCount: 2,
    buyBoxMatchCount: 2,
    source: "Local Builder Assoc & REI Meetups",
    source_url: "https://www.biggerpockets.com",
    sourceUrl: "https://www.biggerpockets.com",
    sourceCategory: "REI_MEETUP",
    status: "ACTIVE",
    notes: "Cash buyer looking for 3BR rentals in Memphis and Birmingham.",
    lastContactedAt: "2026-08-17T11:00:00Z",
    lastNotesUpdate: "2026-08-17T11:00:00Z",
    isWholesalerReady: false,
    wholesaleTags: [],
    priority: "MEDIUM",
    acceptsAssignments: false,
  },
];

export const INITIAL_HISTORICAL_SNAPSHOTS: ProfitSnapshot[] = [
  {
    id: "snap-1",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI",
    purchasePrice: 38000,
    totalInvestment: 57000,
    expectedSalePrice: 92000,
    netProceeds: 84640,
    projectedProfit: 27640,
    projectedROI: 48.5,
    stage: "ANALYSIS",
    notes: "Initial Agent 2 algorithmic deep underwriting",
    createdAt: "2026-08-19T08:30:00Z",
  },
  {
    id: "snap-2",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI",
    purchasePrice: 36000,
    totalInvestment: 54800,
    expectedSalePrice: 92000,
    netProceeds: 84640,
    projectedProfit: 29840,
    projectedROI: 54.5,
    stage: "OFFER",
    notes: "Offer submitted with $2,000 negotiated discount",
    createdAt: "2026-08-20T09:00:00Z",
  },
  {
    id: "snap-3",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI",
    purchasePrice: 36500,
    totalInvestment: 55300,
    expectedSalePrice: 92000,
    netProceeds: 84640,
    projectedProfit: 29340,
    projectedROI: 53.1,
    stage: "NEGOTIATION",
    notes: "Seller counter at $36,500 accepted in principle",
    createdAt: "2026-08-20T11:30:00Z",
  },
  {
    id: "snap-4",
    dealId: "deal-2",
    propertyAddress: "1845 Lamar Avenue, Memphis, TN",
    purchasePrice: 44000,
    totalInvestment: 68600,
    expectedSalePrice: 102000,
    netProceeds: 93840,
    projectedProfit: 25240,
    projectedROI: 36.8,
    stage: "ANALYSIS",
    notes: "Agent 2 initial underwriting",
    createdAt: "2026-08-19T10:00:00Z",
  },
];

export const INITIAL_REALIZED_DEALS: RealizedDealData[] = [
  {
    dealId: "deal-past-1",
    actualPurchasePrice: 32000,
    actualRepairCosts: 11500,
    actualClosingCosts: 1100,
    actualHoldingCosts: 1400,
    actualFinancingCosts: 900,
    actualOtherCosts: 300,
    actualSalePrice: 84000,
    actualSellingCosts: 2500,
    actualCommissions: 4200,
    closedDate: "2026-07-28",
  },
  {
    dealId: "deal-past-2",
    actualPurchasePrice: 41000,
    actualRepairCosts: 15200,
    actualClosingCosts: 1450,
    actualHoldingCosts: 1900,
    actualFinancingCosts: 1100,
    actualOtherCosts: 450,
    actualSalePrice: 96500,
    actualSellingCosts: 2895,
    actualCommissions: 4825,
    closedDate: "2026-08-05",
  },
];

export const INITIAL_CONTRACTS: ContractDraft[] = [
  {
    id: "cnt-1",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI 48202",
    type: "PURCHASE_AND_SALE",
    buyerName: "DealHunter Capital LLC (and/or Assigns)",
    sellerName: "Wayne County Holdings Group LLC",
    purchasePrice: 36500,
    earnestMoney: 2500,
    inspectionPeriodDays: 7,
    closingPeriodDays: 14,
    assignmentFee: 7500,
    contingencies: [
      "Satisfactory inspection within 7 business days",
      "Marketable title free and clear of all liens and encumbrances",
      "Buyer assigns rights clause fully permissible",
    ],
    status: "PENDING_APPROVAL",
    documentText: `REAL ESTATE PURCHASE AND SALE AGREEMENT\n\n1. PARTIES: Buyer (DealHunter Capital LLC & Assigns) and Seller (Wayne County Holdings Group LLC).\n2. PROPERTY: 742 Oak Street, Detroit, MI 48202 (Parcel: 01004829.001).\n3. PURCHASE PRICE: $36,500.00 USD paid in certified cash funds at closing.\n4. EARNEST MONEY: $2,500.00 to be deposited with First American Title within 48 hours of mutual execution.\n5. INSPECTION: 7 business days right to inspect and terminate for any reason with full refund of earnest deposit.\n6. CLOSING: On or before 14 calendar days from execution.\n7. ASSIGNMENT: Buyer retains unconditional right to assign this agreement.`,
    createdAt: "2026-08-20T12:00:00Z",
    updatedAt: "2026-08-20T12:00:00Z",
  },
];

export const INITIAL_APPROVALS: ApprovalRequest[] = [
  {
    id: "appr-1",
    action: "Authorize Binding Purchase Agreement Submission",
    type: "SUBMIT_OFFER",
    dealId: "deal-1",
    propertyAddress: "742 Oak Street, Detroit, MI",
    details: {
      offeredPrice: 36500,
      earnestMoney: 2500,
      inspectionDays: 7,
      projectedProfit: 29340,
      projectedROI: "53.1%",
    },
    status: "PENDING",
    requestedBy: "DEALHUNTER",
    createdAt: "2026-08-20T12:15:00Z",
  },
  {
    id: "appr-2",
    action: "Send Direct Outreach to Listing Agent (Tasha Holloway)",
    type: "SEND_OUTREACH",
    dealId: "deal-2",
    propertyAddress: "1845 Lamar Avenue, Memphis, TN",
    details: {
      recipient: "tasha@bluffcityproperties.com",
      channel: "EMAIL",
      proposedOffer: 42000,
    },
    status: "PENDING",
    requestedBy: "OUTREACH",
    createdAt: "2026-08-20T12:45:00Z",
  },
];

// --- Dedicated Land Wholesaling Sellers & Motivated Owners ---
export const INITIAL_SELLERS: SellerRecord[] = [
  {
    id: "seller-1",
    name: "Karen Whitfield",
    propertyAddress: "Tract 9 Cumberland Ridge Road",
    city: "Crossville",
    state: "TN",
    zip: "38555",
    propertyType: "land",
    lotSizeAcres: 28.0,
    sqft: 1219680,
    askingPrice: 120000,
    estimatedValue: 235000,
    estimatedRepairs: 8000,
    phone: "(931) 555-4819",
    email: "karen.whitfield@gmail.com",
    status: "NEGOTIATING",
    source: "LandWatch",
    source_url: "https://www.landwatch.com",
    sourceCategory: "PUBLIC_LISTING",
    fitReason: "Found via LandWatch listing search. Motivated seller with 28 unrestricted timber acres.",
    notes: "Inherited Cumberland plateau acreage. Open to $105,000 cash for rapid 14-day close.",
    lastContactedAt: "2026-08-20T08:00:00Z",
    lastNotesUpdate: "2026-08-20T08:00:00Z",
    createdAt: "2026-08-19T10:00:00Z",
    updatedAt: "2026-08-20T08:00:00Z",
  },
  {
    id: "seller-2",
    name: "Tom Reyes",
    propertyAddress: "Highway 281 & Ranch Road 1320",
    city: "Johnson City",
    state: "TX",
    zip: "78636",
    propertyType: "land",
    lotSizeAcres: 14.5,
    sqft: 631620,
    askingPrice: 210000,
    estimatedValue: 380000,
    estimatedRepairs: 15000,
    phone: "(512) 555-2940",
    email: "tom.reyes@reyesranches.com",
    status: "CONTACTED",
    source: "Land And Farm",
    source_url: "https://www.landandfarm.com",
    sourceCategory: "PUBLIC_LISTING",
    fitReason: "Found via Land And Farm listing search. Motivated ranch liquidation, 14.5 acres in Blanco County.",
    notes: "Has 14.5 acre parcel in Texas Hill Country with live oak trees and AG exemption. Seeking clean cash buyer.",
    lastContactedAt: "2026-08-16T10:00:00Z",
    lastNotesUpdate: "2026-08-16T10:00:00Z",
    createdAt: "2026-08-16T09:00:00Z",
    updatedAt: "2026-08-16T10:00:00Z",
  },
  {
    id: "seller-3",
    name: "Delores Nguyen",
    propertyAddress: "8920 E Sonoran Vista Parkway",
    city: "Scottsdale",
    state: "AZ",
    zip: "85262",
    propertyType: "land",
    lotSizeAcres: 5.2,
    sqft: 226512,
    askingPrice: 465000,
    estimatedValue: 720000,
    estimatedRepairs: 18000,
    phone: "(480) 555-7728",
    email: "delores.nguyen@outlook.com",
    status: "NEW",
    source: "County Assessor (Delinquent Tax)",
    source_url: "https://mcassessor.maricopa.gov",
    sourceCategory: "OFF_MARKET_TAX",
    fitReason: "Found via Maricopa County Assessor delinquent tax records. 5.2-acre Scottsdale luxury homesite with $4,200 back taxes.",
    notes: "Out-of-state heir with 5.2 custom acres near McDowell Preserve. Wants to avoid tax auction.",
    lastContactedAt: "2026-08-15T09:00:00Z",
    lastNotesUpdate: "2026-08-15T09:00:00Z",
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-08-15T09:00:00Z",
  },
  {
    id: "seller-4",
    name: "Harold & Beatrice Sterling",
    propertyAddress: "2214 N 24th Street",
    city: "Tampa",
    state: "FL",
    zip: "33605",
    propertyType: "land",
    lotSizeAcres: 0.35,
    sqft: 15246,
    askingPrice: 79000,
    estimatedValue: 145000,
    estimatedRepairs: 6000,
    phone: "(813) 555-9182",
    email: "hbsterling@verizon.net",
    status: "UNDER_CONTRACT",
    source: "Lands of America",
    source_url: "https://www.landsofamerica.com",
    sourceCategory: "PUBLIC_LISTING",
    fitReason: "Found via Lands of America direct feed. Shovel-ready infill duplex parcel in Ybor corridor.",
    notes: "Contract locked at $76,000 cash. Title search clear.",
    lastContactedAt: "2026-08-20T10:00:00Z",
    lastNotesUpdate: "2026-08-20T10:00:00Z",
    createdAt: "2026-08-18T14:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "seller-5",
    name: "Arthur Pendelton",
    propertyAddress: "4410 NW 39th Expressway",
    city: "Oklahoma City",
    state: "OK",
    zip: "73112",
    propertyType: "land",
    lotSizeAcres: 2.8,
    sqft: 121968,
    askingPrice: 185000,
    estimatedValue: 325000,
    estimatedRepairs: 12000,
    phone: "(405) 555-6619",
    email: "pendelton.holdings@gmail.com",
    status: "CONTACTED",
    source: "PropStream Off-Market",
    source_url: "https://www.propstream.com",
    sourceCategory: "OFF_MARKET_TAX",
    fitReason: "Found via PropStream high-equity absentee owner filter. Commercial zoning corridor parcel.",
    notes: "Owner retired and living in Texas. Considering $165,000 all-cash.",
    lastContactedAt: "2026-08-16T11:00:00Z",
    lastNotesUpdate: "2026-08-16T11:00:00Z",
    createdAt: "2026-08-16T11:00:00Z",
    updatedAt: "2026-08-16T11:00:00Z",
  },
];

// --- Dedicated Land Wholesaling Buyers & Builders ---
export const INITIAL_BUYERS: BuyerRecord[] = [
  {
    id: "buyer-1",
    name: "Desert Ridge Builders",
    company: "Desert Ridge Construction & Development LLC",
    phone: "(480) 555-9201",
    email: "acquisitions@desertridgebuilders.com",
    targetMarkets: ["AZ", "NV", "UT"],
    targetTypes: ["land", "single_family"],
    maxBudget: 3200000,
    minROI: 20,
    status: "ACTIVE",
    source: "BiggerPockets",
    source_url: "https://www.biggerpockets.com",
    sourceCategory: "BIGGERPOCKETS",
    buyBoxSummary: "Custom spec builders seeking 1 to 10-acre infill residential parcels in Maricopa and Pinal counties.",
    notes: "Prefers paved road frontage with power/water meter boxes installed. Can close in 7 days.",
    lastContactedAt: "2026-08-20T11:30:00Z",
    lastNotesUpdate: "2026-08-20T11:30:00Z",
    createdAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-08-20T11:30:00Z",
  },
  {
    id: "buyer-2",
    name: "Sonoran Land Holdings",
    company: "Sonoran Land Syndicate LLC",
    phone: "(520) 555-3819",
    email: "deals@sonoranlandholdings.com",
    targetMarkets: ["AZ", "TX", "NM"],
    targetTypes: ["land"],
    maxBudget: 1800000,
    minROI: 25,
    status: "ACTIVE",
    source: "Facebook Land Groups",
    source_url: "https://www.facebook.com/groups",
    sourceCategory: "FACEBOOK_GROUPS",
    buyBoxSummary: "High-desert raw acreage and rural subdivide parcels. Minimum 5+ acres.",
    notes: "Aggressive cash buyers for mountain views and unrestricted zoning.",
    lastContactedAt: "2026-08-19T14:10:00Z",
    lastNotesUpdate: "2026-08-19T14:10:00Z",
    createdAt: "2026-08-12T12:00:00Z",
    updatedAt: "2026-08-19T14:10:00Z",
  },
  {
    id: "buyer-3",
    name: "Terra Land Syndicate & Infill Fund",
    company: "Terra Capital Partners LLC",
    phone: "(512) 555-4890",
    email: "acquisitions@terralandfund.com",
    targetMarkets: ["TX", "FL", "AZ", "TN", "OK"],
    targetTypes: ["land"],
    maxBudget: 2500000,
    minROI: 25,
    status: "ACTIVE",
    source: "LandModo Dispo Network",
    source_url: "https://www.landmodo.com",
    sourceCategory: "LANDMODO",
    buyBoxSummary: "Shovel-ready builder infill lots and subdividable 10-50 acre tracts in Sunbelt.",
    notes: "Has $2.5M capital deployed with immediate wire authorization.",
    lastContactedAt: "2026-08-18T16:00:00Z",
    lastNotesUpdate: "2026-08-18T16:00:00Z",
    createdAt: "2026-08-14T09:00:00Z",
    updatedAt: "2026-08-18T16:00:00Z",
  },
  {
    id: "buyer-4",
    name: "Apex Capital Partners",
    company: "Apex Real Estate Holdings LLC",
    phone: "(312) 555-7800",
    email: "acquisitions@apexreholding.com",
    targetMarkets: ["MI", "OH", "IN"],
    targetTypes: ["single_family", "multifamily"],
    maxBudget: 850000,
    minROI: 24,
    status: "ACTIVE",
    source: "BiggerPockets",
    source_url: "https://www.biggerpockets.com",
    sourceCategory: "BIGGERPOCKETS",
    buyBoxSummary: "Midwest turnkey rentals and deep discount cosmetic flips.",
    notes: "Has bought 3 properties from us in Wayne County.",
    lastContactedAt: "2026-08-20T10:00:00Z",
    lastNotesUpdate: "2026-08-20T10:00:00Z",
    createdAt: "2026-08-01T08:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
];

// --- Property Inspections Synced from Deals ---
export const INITIAL_PROPERTY_INSPECTIONS: PropertyInspection[] = [
  {
    id: "insp-1",
    dealId: "deal-1",
    propertyId: "prop-1",
    propertyAddress: "742 Oak Street",
    city: "Detroit",
    state: "MI",
    zip: "48202",
    inspectionType: "PHYSICAL_STRUCTURAL",
    scheduledDate: "2026-08-27",
    deadlineDate: "2026-08-29",
    inspectorName: "David Kowalski, CMI",
    inspectorCompany: "Motor City Precision Inspections",
    inspectorPhone: "(313) 555-4921",
    status: "SCHEDULED",
    contingencyDaysLeft: 5,
    cost: 450,
    findingsSummary: "Scheduled general structural, foundation settlement check & crawlspace moisture audit.",
    criticalIssuesCount: 0,
    reportUrl: "https://reports.inspectpro.com/det-742-oak",
  },
  {
    id: "insp-2",
    dealId: "deal-1",
    propertyId: "prop-1",
    propertyAddress: "742 Oak Street",
    city: "Detroit",
    state: "MI",
    zip: "48202",
    inspectionType: "SEWER_LATERAL",
    scheduledDate: "2026-08-26",
    deadlineDate: "2026-08-29",
    inspectorName: "Ray Vance",
    inspectorCompany: "Detroit HydroScope Lateral Video",
    inspectorPhone: "(313) 555-8833",
    status: "SCHEDULED",
    contingencyDaysLeft: 4,
    cost: 275,
    findingsSummary: "CCTV scope from cleanout to municipal main line to rule out tree root collapse.",
    criticalIssuesCount: 0,
  },
  {
    id: "insp-3",
    dealId: "deal-2",
    propertyId: "prop-2",
    propertyAddress: "1845 Lamar Avenue",
    city: "Memphis",
    state: "TN",
    zip: "38114",
    inspectionType: "PEST_TERMITE",
    scheduledDate: "2026-08-25",
    deadlineDate: "2026-08-28",
    inspectorName: "Curtis Washington",
    inspectorCompany: "Bluff City Pest & Termite Certification",
    inspectorPhone: "(901) 555-3109",
    status: "IN_PROGRESS",
    contingencyDaysLeft: 3,
    cost: 150,
    findingsSummary: "Wood-destroying organism (WDO) clearance required for investor assignment closing.",
    criticalIssuesCount: 0,
  },
  {
    id: "insp-4",
    dealId: "deal-11",
    propertyId: "prop-11",
    propertyAddress: "8920 E Sonoran Vista Parkway",
    city: "Scottsdale",
    state: "AZ",
    zip: "85262",
    inspectionType: "SOIL_PERC",
    scheduledDate: "2026-08-28",
    deadlineDate: "2026-09-03",
    inspectorName: "Craig Henderson, PE",
    inspectorCompany: "Sonoran Geotech & Perc Engineering",
    inspectorPhone: "(480) 555-6204",
    status: "SCHEDULED",
    contingencyDaysLeft: 9,
    cost: 1200,
    findingsSummary: "Soil percolation test & alternative septic field feasibility for luxury custom home.",
    criticalIssuesCount: 0,
  },
  {
    id: "insp-5",
    dealId: "deal-12",
    propertyId: "prop-12",
    propertyAddress: "Tract 9 Cumberland Ridge Road",
    city: "Crossville",
    state: "TN",
    zip: "38555",
    inspectionType: "TITLE_SURVEY",
    scheduledDate: "2026-08-29",
    deadlineDate: "2026-09-05",
    inspectorName: "Hoyt Sterling, PLS",
    inspectorCompany: "Cumberland Boundary & Title Surveyors",
    inspectorPhone: "(931) 555-7781",
    status: "SCHEDULED",
    contingencyDaysLeft: 11,
    cost: 1800,
    findingsSummary: "Boundary corner pin verification and 650ft highway easement legal recording.",
    criticalIssuesCount: 0,
  },
  {
    id: "insp-6",
    dealId: "deal-10",
    propertyId: "prop-10",
    propertyAddress: "2214 N 24th Street",
    city: "Tampa",
    state: "FL",
    zip: "33605",
    inspectionType: "ENVIRONMENTAL_PHASE1",
    scheduledDate: "2026-08-24",
    deadlineDate: "2026-08-27",
    inspectorName: "Elena Vasquez, REM",
    inspectorCompany: "Gulf Coast Environmental Assessors",
    inspectorPhone: "(813) 555-9012",
    status: "PASSED",
    contingencyDaysLeft: 2,
    cost: 950,
    findingsSummary: "Zero environmental contaminants or wetland buffer restrictions detected. Clean ESA Phase 1.",
    criticalIssuesCount: 0,
    reportUrl: "https://reports.inspectpro.com/tpa-2214-phase1",
  },
];

// --- Comprehensive Real Estate Lead Sourcing Platforms Knowledge ---
export const LAND_SOURCING_PLATFORMS = {
  acquisitions: [
    { name: "LandWatch", type: "PUBLIC_MLS", url: "https://www.landwatch.com", desc: "High-volume rural parcels, hunting tracts, and owner-financed acreage" },
    { name: "Land And Farm", type: "PUBLIC_MLS", url: "https://www.landandfarm.com", desc: "Farms, ranches, timberland, and rural residential land listings" },
    { name: "Lands of America", type: "PUBLIC_MLS", url: "https://www.landsofamerica.com", desc: "Commercial acreage, country estates, and mountain tracts" },
    { name: "County Tax Assessor (Delinquent Records)", type: "OFF_MARKET", url: "https://mcassessor.maricopa.gov", desc: "Direct tax lien lists, overdue municipal levies, and absentee inherited estates" },
    { name: "PropStream / DataTree", type: "OFF_MARKET", url: "https://www.propstream.com", desc: "Filtered lists: out-of-state owners, 100% equity, pre-foreclosure land" },
    { name: "Satellite Reconnaissance & GIS Maps", type: "OFF_MARKET", url: "https://earth.google.com", desc: "Vacant parcel visual spotter, road frontage verification, and infill discovery" },
    { name: "FSBO.com & Craigslist Land", type: "PUBLIC_MLS", url: "https://www.craigslist.org", desc: "Direct motivated FSBO sellers avoiding broker commissions" },
  ],
  disposition: [
    { name: "BiggerPockets Investor Network", type: "CASH_BUYER_NETWORK", url: "https://www.biggerpockets.com", desc: "Verified cash buyers, turnkey builders, and land syndicates" },
    { name: "Facebook Land Investor Groups", type: "COMMUNITY", url: "https://www.facebook.com/groups", desc: "Active local state land wholesalers, flippers, and subdividers" },
    { name: "LandModo & LandHub Dispo", type: "PLATFORM", url: "https://www.landmodo.com", desc: "National network for wholesale dispo listings and cash investor blasts" },
    { name: "Local Home Builders Associations", type: "BUILDER_NETWORK", url: "https://www.nahb.org", desc: "Custom home builders looking for shovel-ready infill lots" },
    { name: "County Recorder Cash Buyers List", type: "PUBLIC_RECORD", url: "https://countyrecorder.gov", desc: "Investors who bought land for cash in the last 12 months" },
  ],
};
