import React, { useState, useMemo } from "react";
import {
  FileBarChart2,
  Download,
  Copy,
  Check,
  Printer,
  Calendar,
  Zap,
  TrendingUp,
  Award,
  ShieldCheck,
  Clock,
  Sparkles,
  ChevronRight,
  X,
  Share2,
  FileText,
  Percent,
} from "lucide-react";
import { AgentPerformanceReportData } from "../types";
import { store } from "../services/store";

interface AgentPerformanceReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function AgentPerformanceReportModal({
  isOpen,
  onClose,
}: AgentPerformanceReportModalProps) {
  const [selectedPeriod, setSelectedPeriod] = useState<
    "THIS_WEEK" | "LAST_7_DAYS" | "MONTH_TO_DATE" | "ALL_TIME"
  >("THIS_WEEK");
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"EXECUTIVE" | "METRICS" | "TRENDS" | "EXPORT">("EXECUTIVE");

  const reportData = useMemo(() => {
    return store.generateAgentPerformanceReport(selectedPeriod);
  }, [selectedPeriod, isOpen]);

  if (!isOpen) return null;

  const handleCopySummary = () => {
    const textSummary = `=====================================================
DEALHUNTER AI — AGENT PERFORMANCE & VELOCITY REPORT
Report ID: ${reportData.reportId}
Period: ${reportData.period} (${reportData.startDate} to ${reportData.endDate})
Overall Swarm Score: ${reportData.overallScore}/100
=====================================================

EXECUTIVE SUMMARY:
${reportData.executiveSummary}

KEY PERFORMANCE INDICATORS:
- Total Pipeline Volume: $${reportData.totalPipelineVolume.toLocaleString()}
- Total Projected Gross Profit: $${reportData.totalProjectedProfit.toLocaleString()}
- Realized Settled Escrow Profit: $${reportData.realizedProfitSettled.toLocaleString()}
- Lead-to-Contract Conversion Rate: ${reportData.conversionRatePercent}%

AGENT VELOCITY BREAKDOWN:
${reportData.agentMetrics
  .map(
    (a) => `• ${a.title}
  - Throughput: ${a.throughputCount} items processed
  - Average Latency: ${a.avgLatencyMs}ms
  - Success Rate: ${a.successRatePct}% (Error: ${a.errorRatePct}%)
  - Speed / Accuracy: ${a.speedScore}/100 | ${a.accuracyScore}/100
  - Key Impact: ${a.topAccomplishment}`
  )
  .join("\n\n")}

WEEKLY VELOCITY TRENDS:
${reportData.weeklyVelocityTrends
  .map(
    (t) =>
      `${t.day}: Discovered ${t.dealsDiscovered} | Analyzed ${t.underwritten} | Outreach ${t.outreachSent} | Contracts ${t.contractsDrafted} | Spread $${t.projectedSpread.toLocaleString()}`
  )
  .join("\n")}

STRATEGIC RECOMMENDATIONS:
${reportData.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

Generated by DealHunter Autonomous Swarm at ${new Date(reportData.generatedAt).toLocaleString()}
=====================================================`;

    navigator.clipboard.writeText(textSummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadMarkdown = () => {
    const markdownContent = `# DEALHUNTER AI — AGENT PERFORMANCE & VELOCITY REPORT
**Report ID**: \`${reportData.reportId}\`  
**Generated At**: ${new Date(reportData.generatedAt).toLocaleString()}  
**Evaluation Window**: ${reportData.startDate} to ${reportData.endDate} (${reportData.period})  
**Swarm Efficiency Score**: **${reportData.overallScore}/100**

---

## 1. Executive Summary
${reportData.executiveSummary}

---

## 2. Core Stakeholder Metrics
| Metric | Value | Status |
| :--- | :--- | :--- |
| **Total Pipeline Volume** | **$${reportData.totalPipelineVolume.toLocaleString()}** | Active Qualified Deals |
| **Projected Gross Assignment Profit** | **$${reportData.totalProjectedProfit.toLocaleString()}** | Target ROI ≥ 25% |
| **Settled Realized Profit** | **$${reportData.realizedProfitSettled.toLocaleString()}** | Escrow Disbursed |
| **Outreach Conversion Velocity** | **${reportData.conversionRatePercent}%** | Reply & LOI Acceptance |

---

## 3. Agent Velocity & Latency Scorecard
${reportData.agentMetrics
  .map(
    (a) => `### ${a.title}
- **Throughput**: ${a.throughputCount} executions
- **Average Engine Latency**: \`${a.avgLatencyMs}ms\`
- **Success / Accuracy**: ${a.successRatePct}% (Speed: ${a.speedScore}/100, Accuracy: ${a.accuracyScore}/100)
- **Top Accomplishment**: *${a.topAccomplishment}*
`
  )
  .join("\n")}

---

## 4. Weekly Velocity Matrix
| Day | Discovered | Underwritten | Outreach Sent | Contracts Drafted | Projected Spread |
| :--- | :---: | :---: | :---: | :---: | :--- |
${reportData.weeklyVelocityTrends
  .map(
    (t) =>
      `| ${t.day} | ${t.dealsDiscovered} | ${t.underwritten} | ${t.outreachSent} | ${t.contractsDrafted} | $${t.projectedSpread.toLocaleString()} |`
  )
  .join("\n")}

---

## 5. Strategic Directives & Recommendations
${reportData.recommendations.map((r, i) => `${i + 1}. **${r}**`).join("\n")}
`;

    const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Agent-Performance-Report-${reportData.reportId}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(reportData, null, 2)], {
      type: "application/json;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Agent-Performance-Report-${reportData.reportId}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      id="performance-report-backdrop"
      className="fixed inset-0 z-[9999] bg-black/80 backdrop-blur-md flex items-center justify-center p-3 sm:p-6 animate-in fade-in duration-150"
      onClick={onClose}
    >
      <div
        id="performance-report-modal"
        className="w-full max-w-4xl bg-slate-900 border border-slate-700/80 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-150"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/70">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-emerald-950/80 text-emerald-400 border border-emerald-500/30">
              <FileBarChart2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base sm:text-lg font-bold text-slate-100">
                  Agent Performance & Velocity Report
                </h2>
                <span className="text-[11px] font-mono px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 font-semibold">
                  {reportData.reportId}
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Synthesizing autonomous agent execution, MAO underwriting latency, and ROI velocity
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              id="btn-print-report"
              onClick={handlePrint}
              className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              title="Printable View"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-slate-200 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Period Selector & Action Bar */}
        <div className="px-6 py-3 bg-slate-950/40 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
          {/* Period selector */}
          <div className="flex items-center gap-1.5 p-1 bg-slate-950 rounded-lg border border-slate-800">
            {(
              [
                { id: "THIS_WEEK", label: "This Week" },
                { id: "LAST_7_DAYS", label: "Last 7 Days" },
                { id: "MONTH_TO_DATE", label: "Month to Date" },
                { id: "ALL_TIME", label: "All Time" },
              ] as const
            ).map((p) => (
              <button
                key={p.id}
                type="button"
                id={`btn-report-period-${p.id}`}
                onClick={() => setSelectedPeriod(p.id)}
                className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                  selectedPeriod === p.id
                    ? "bg-emerald-600 text-white shadow-sm"
                    : "text-slate-400 hover:text-slate-200"
                }`}
              >
                {p.label}
              </button>
            ))}
          </div>

          {/* Export Action Buttons */}
          <div className="flex items-center gap-2">
            <button
              type="button"
              id="btn-copy-report-summary"
              onClick={handleCopySummary}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? "Copied!" : "Copy Summary"}</span>
            </button>
            <button
              type="button"
              id="btn-download-report-md"
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white shadow-sm transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Markdown</span>
            </button>
            <button
              type="button"
              id="btn-download-report-json"
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-all"
            >
              <FileText className="w-3.5 h-3.5" />
              <span>JSON</span>
            </button>
          </div>
        </div>

        {/* Tab Selection */}
        <div className="px-6 border-b border-slate-800 flex gap-4 text-xs font-medium text-slate-400">
          {(
            [
              { id: "EXECUTIVE", label: "Executive Overview" },
              { id: "METRICS", label: "Agent Scorecards (4/4)" },
              { id: "TRENDS", label: "Velocity & Day Trends" },
              { id: "EXPORT", label: "Stakeholder Summary" },
            ] as const
          ).map((t) => (
            <button
              key={t.id}
              type="button"
              onClick={() => setActiveTab(t.id)}
              className={`py-2.5 border-b-2 font-semibold transition-all ${
                activeTab === t.id
                  ? "border-emerald-500 text-emerald-400"
                  : "border-transparent text-slate-400 hover:text-slate-200"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* Body Content */}
        <div className="p-6 overflow-y-auto space-y-6 max-h-[60vh] custom-scrollbar">
          {activeTab === "EXECUTIVE" && (
            <div className="space-y-6">
              {/* Executive Summary Banner */}
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800/80 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-emerald-400 font-mono">
                    <Sparkles className="w-4 h-4" />
                    <span>Executive AI Swarm Synthesis</span>
                  </div>
                  <span className="text-xs font-mono text-slate-500">
                    Range: {reportData.startDate} → {reportData.endDate}
                  </span>
                </div>
                <p className="text-sm text-slate-300 leading-relaxed font-normal">
                  {reportData.executiveSummary}
                </p>
              </div>

              {/* 4 Core Metrics Grid */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="text-[11px] text-slate-400 font-medium">Pipeline Volume</span>
                  <div className="text-xl font-bold text-slate-100 mt-1">
                    ${reportData.totalPipelineVolume.toLocaleString()}
                  </div>
                  <span className="text-[10px] text-emerald-400 font-mono mt-1 block">
                    ↑ 14 Qualified Listings
                  </span>
                </div>

                <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="text-[11px] text-slate-400 font-medium">Projected Gross Profit</span>
                  <div className="text-xl font-bold text-emerald-400 mt-1">
                    ${reportData.totalProjectedProfit.toLocaleString()}
                  </div>
                  <span className="text-[10px] text-slate-400 font-mono mt-1 block">
                    Avg Spread: $32,000/deal
                  </span>
                </div>

                <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="text-[11px] text-slate-400 font-medium">Settled Realized Profit</span>
                  <div className="text-xl font-bold text-blue-400 mt-1">
                    ${reportData.realizedProfitSettled.toLocaleString()}
                  </div>
                  <span className="text-[10px] text-blue-400/80 font-mono mt-1 block">
                    Escrow Ready Funds
                  </span>
                </div>

                <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="text-[11px] text-slate-400 font-medium">Outreach Conversion</span>
                  <div className="text-xl font-bold text-amber-400 mt-1">
                    {reportData.conversionRatePercent}%
                  </div>
                  <span className="text-[10px] text-emerald-400 font-mono mt-1 block">
                    0 Spam Flags Triggered
                  </span>
                </div>
              </div>

              {/* Strategic Recommendations */}
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 font-mono flex items-center gap-2">
                  <TrendingUp className="w-4 h-4 text-emerald-400" />
                  <span>Strategic Agent Optimization Recommendations</span>
                </h4>
                <div className="space-y-2">
                  {reportData.recommendations.map((rec, i) => (
                    <div key={i} className="flex items-start gap-2.5 text-xs text-slate-300">
                      <span className="px-1.5 py-0.5 rounded bg-slate-800 font-mono text-emerald-400 text-[10px] shrink-0">
                        0{i + 1}
                      </span>
                      <span>{rec}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeTab === "METRICS" && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {reportData.agentMetrics.map((agent) => (
                  <div
                    key={agent.name}
                    className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3"
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <h4 className="text-sm font-bold text-slate-100">{agent.title}</h4>
                        <span className="text-[11px] text-slate-400">
                          {agent.dealsProcessed} deals evaluated
                        </span>
                      </div>
                      <div className="text-right">
                        <span className="text-xs font-bold text-emerald-400 font-mono">
                          {agent.successRatePct}% Success
                        </span>
                        <span className="text-[10px] text-slate-500 font-mono block">
                          {agent.avgLatencyMs}ms Latency
                        </span>
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-2 pt-2 border-t border-slate-800/80 text-xs">
                      <div>
                        <span className="text-slate-500">Speed Rating:</span>{" "}
                        <span className="font-semibold text-slate-200">{agent.speedScore}/100</span>
                      </div>
                      <div>
                        <span className="text-slate-500">Accuracy Rating:</span>{" "}
                        <span className="font-semibold text-slate-200">{agent.accuracyScore}/100</span>
                      </div>
                    </div>

                    <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-300 flex items-start gap-2">
                      <Award className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                      <span>{agent.topAccomplishment}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === "TRENDS" && (
            <div className="space-y-4">
              <div className="overflow-x-auto">
                <table className="w-full text-xs text-left border-collapse">
                  <thead>
                    <tr className="border-b border-slate-800 text-slate-400 font-mono text-[11px] uppercase">
                      <th className="py-2.5 px-3">Day</th>
                      <th className="py-2.5 px-3">Discovered</th>
                      <th className="py-2.5 px-3">Underwritten</th>
                      <th className="py-2.5 px-3">Outreach</th>
                      <th className="py-2.5 px-3">Contracts</th>
                      <th className="py-2.5 px-3 text-right">Projected Spread</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/60 font-mono">
                    {reportData.weeklyVelocityTrends.map((trend) => (
                      <tr key={trend.day} className="hover:bg-slate-800/30 transition-colors">
                        <td className="py-2.5 px-3 font-bold text-slate-200">{trend.day}</td>
                        <td className="py-2.5 px-3 text-slate-300">{trend.dealsDiscovered}</td>
                        <td className="py-2.5 px-3 text-blue-300">{trend.underwritten}</td>
                        <td className="py-2.5 px-3 text-amber-300">{trend.outreachSent}</td>
                        <td className="py-2.5 px-3 text-purple-300">{trend.contractsDrafted}</td>
                        <td className="py-2.5 px-3 text-right text-emerald-400 font-semibold">
                          ${trend.projectedSpread.toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {activeTab === "EXPORT" && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 font-mono">
                    Formatted Stakeholder Text Preview
                  </h4>
                  <button
                    type="button"
                    onClick={handleCopySummary}
                    className="text-xs text-emerald-400 hover:text-emerald-300 font-medium"
                  >
                    {copied ? "Copied to Clipboard!" : "Copy Raw Text"}
                  </button>
                </div>
                <textarea
                  readOnly
                  rows={10}
                  className="w-full bg-slate-900 border border-slate-800 rounded-lg p-3 text-xs font-mono text-slate-300 leading-relaxed outline-none"
                  value={`DEALHUNTER AI — AGENT PERFORMANCE & VELOCITY REPORT\nReport ID: ${reportData.reportId}\nPeriod: ${reportData.period}\nSwarm Score: ${reportData.overallScore}/100\n\nExecutive Summary:\n${reportData.executiveSummary}\n\nPipeline Volume: $${reportData.totalPipelineVolume.toLocaleString()}\nProjected Gross Profit: $${reportData.totalProjectedProfit.toLocaleString()}\nConversion Velocity: ${reportData.conversionRatePercent}%\n\nDirectives:\n${reportData.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}`}
                />
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 bg-slate-950 border-t border-slate-800 flex items-center justify-between text-xs text-slate-500 font-mono">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
            <span>All 4 Autonomous Agents Verified</span>
          </div>
          <span>Report Generated: {new Date(reportData.generatedAt).toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}
